version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs

services:

  dind:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases: 
          - docker
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    container_name: jenkins-blueocean
    image: jenkinsci/blueocean
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
